import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { SessionProvider, signOut } from "next-auth/react"
import { signIn,useSession } from "next-auth/react";
import Expanded from "../components/Expanded"
import Button from "../components/Button";
import { useState } from "react";
import Navbar from "@/components/Navbar";



const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [exp,setexp]=useState(false)

  const {data:session}=useSession()

console.log(session);
const HandleClick=()=>{
    
}

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-orange-100 min-h-screen">
        welcome {session?.user?.email}
        {!session?.user && <button onClick={() => signIn()}>sign in</button>}
        <Navbar title="Title"/>
        paradigm mein paisa chahiye.
        <button onClick={()=>signIn()}>sign in</button>
        <button onClick={()=>signOut()}>sign out</button>
        {session?.user?.name}
        <Expanded bgColor="bg-orange-300" title="lorem ipsum" content="ya iski maa ki chu"/>
        
        <Button></Button>
      </div>
    </>
  );
}
