import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { SessionProvider } from "next-auth/react"
import { signIn,useSession } from "next-auth/react";



const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const {data:session}=useSession()

console.log(session?.user);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-slate-700 min-h-screen">
        paradigm mein paisa chahiye.
        <button onClick={()=>signIn()}>sign in</button>
        {session?.user?.name}
        
      </div>
    </>
  );
}
